### ISSUE TITLE
Japanese arabic numbers

### ISSUE THREAD

**Issue by nikolajkb** [takumakanari/japanese-numbers-python#7]
The library can't handle the Japanese (full width) versions of the Arabic numbers.
That is, １２３４万 does not work, but 1234万 does.

I fixed it in my code by pre-processing the input like so:
`def convert_number_chars(nr):
    return "".join([convert_number_char(c) for c in nr])

def convert_number_char(c):
    return {
        "１": "1",
        "２": "2",
        "３": "3",
        "４": "4",
        "５": "5",
        "６": "6",
        "７": "7",
        "８": "8",
        "９": "9",
        "０": "0",
    }.get(c,c)`

**Comment by takumakanari** [comment]
Fixed at https://github.com/takumakanari/japanese-numbers-python/pull/8 .

Thanks for your report @nikolajkb .
